In [3]:
print("Ejercicio 1 Clase 1")
import numpy as np

def vector_norm_l0(matrix):
    mask = matrix > 0
    return np.sum(mask, axis=1)

def vector_norm_l1(matrix):
    abs_m = np.abs(matrix)
    return np.sum(abs_m, axis=1)

def vector_norm_l2(matrix):
    return np.sqrt(np.sum(matrix ** 2, axis=2))

def vector_norm_inf(m):
    return np.max(m, axis=1)


Ejercicio 1 Clase 1


In [10]:
print("Ejercicio 2 Clase 1")

def sorting_vectors_by_norm_l2(matrix):
    norm_l2 = vector_norm_l2(matrix)
    print(norm_l2)
    arg_sort = np.argsort(norm_l2 * -1)
    print(arg_sort)
    return matrix[arg_sort, :]


Ejercicio 2 Clase 1


In [7]:
print("Ejercicio 3 Clase 1")

class index(object):
    def __init__(self, usr_id):
        unique_id = np.unique(usr_id)
        id2idx = np.ones(unique_id.max() + 1, dtype=np.int64) * -1
        id2idx[unique_id] = np.arange(unique_id.size)
        self.id2idx = id2idx
        self.idx2id = unique_id
    
    def get_user_idx(self, ids):
        ids = self.id2idx[ids]
        return ids, ids != -1
    
    def get_user_id(self, idxs):
        return self.idx2id[idxs]

idxManager = index([15, 12, 14, 10, 1, 2, 1])

print(idxManager.get_user_idx(15))
print(idxManager.get_user_idx(12))
print(idxManager.get_user_idx(3))

print(idxManager.get_user_id(0))
print(idxManager.get_user_id(4))

Ejercicio 3 Clase 1
(5, True)
(3, True)
(-1, False)
1
14


In [11]:
print("Ejercicio 4 Clase 1")

truth = np.array([1,1,0,1,1,1,0,0,0,1])
prediction = np.array([1,1,1,1,0,0,1,1,0,0])

TP = np.sum((truth == True) & (prediction == True))
TN = np.sum((truth == False) & (prediction == False))
FN = np.sum((truth == True) & (prediction == False))
FP = np.sum((truth == False) & (prediction == True))

precision = TP / (TP + FP)
recall = TP / (TP + FN)
accuracy = (TP + TN) / (TP + TN + FP + FN)

print("Precision: " + str(precision))
print("Recall: " + str(recall))
print("Accuracy: " + str(accuracy))

Ejercicio 4 Clase 1
Precision: 0.5
Recall: 0.5
Accuracy: 0.4


In [6]:
print("Ejercicio 5 Clase 1")

def avg_q_precision(q_id, truth_relevance):
    unic_id = np.unique(q_id)
    
    q_id_expanded = np.zeros((q_id.size, unic_id.size))
    q_id_expanded = q_id_expanded + q_id[:,np.newaxis]
    
    truth_expanded = np.zeros((truth_relevance.size, unic_id.size))
    truth_expanded = truth_expanded + truth_relevance[:, np.newaxis]
    
    numerators = np.sum((q_id_expanded == unic_id) & (truth_expanded == 1), axis = 0)
    dividers = np.sum(q_id_expanded == unic_id, axis = 0)
    avg_q = np.sum(numerators/dividers)/unic_id.size
    
    return avg_q

qId = np.array([1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4])
truthRelevance = np.array([True, False, True, False, True, True, True, False, False, False, False, False, True, False, False, True])
Test = np.testing.assert_equal(avg_q_precision(qId, truthRelevance), 0.5)

Ejercicio 5 Clase 1
None


In [9]:
print("Ejercicio 6 Clase 1")

vector_X = np.array([[1,2,3],[4,5,6],[7,8,9]])

vector_C = np.array([[1,0,0],[0,1,1]])
C_exp = vector_C[:, np.newaxis]

diff = C_exp-vector_X

distance = vector_norm_l2(diff)

print(distance)

Ejercicio 6 Clase 1
[[ 3.60555128  8.36660027 13.45362405]
 [ 2.44948974  7.54983444 12.72792206]]


In [10]:
print("Ejercicio 7 Clase 1")

min_distance = np.argmin(distance, axis=0)

print(min_distance)

Ejercicio 7 Clase 1
[1 1 1]


In [11]:
print("Ejercicio 8 Clase 1")


Ejercicio 8 Clase 1


In [12]:
print("Ejercicio 9 Clase 1")


Ejercicio 9 Clase 1


In [ ]:
print("Ejercicio 10 Clase 1")
